# This snippet is adapted from graphql-api-for-wp.
#
# GitHub Action: whenever creating a new release of the source code,
# also create a release of the installable plugin.
# Steps to execute:
# - Checkout the source code
# - Create a .zip file, excluding:
#   - All hidden files (.git, .gitignore, etc)
#   - All development files, ending in .dist
#   - All composer files <= after installing dependencies, no need for them anymore
#   - Markdown files concerning development
#   - Folder build/ <= created only to store the .zip file
#   - Folder tests/ <= not needed for the plugin
# - Upload the .zip file as an artifact to the action (this step is possibly optional)
# - Upload the .zip file as a release, for download
name: Generate Installable Plugin, and Upload as Release Asset
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build project
        run: |
          mkdir gravitywp-mp-gf-connector
          rsync -a ./ ./gravitywp-mp-gf-connector --exclude gravitywp-mp-gf-connector
          mkdir build
      - name: Create artifact
        uses: montudor/action-zip@v1
        with:
          args: zip -X -r build/gravitywp-mp-gf-connector-${{ github.event.release.tag_name }}.zip gravitywp-mp-gf-connector -x *.git* *node_modules/\* .* "*/\.*" *CODE_OF_CONDUCT.md *readme-dev.md *.phar *appsero.json *CONTRIBUTING.md *ISSUE_TEMPLATE.md *PULL_REQUEST_TEMPLATE.md *.dist *.neon *composer* *package* *phpunit* *webpack* *tests**
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gravitywp-mp-gf-connector
          path: build/gravitywp-mp-gf-connector-${{ github.event.release.tag_name }}.zip
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/gravitywp-mp-gf-connector-${{ github.event.release.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ github.token }}
