# Deploy to SVN workflow
name: Generate Installable Plugin, Upload as Release Asset, Create a draft PaddlePress Download on my.gravitywp.com

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
      # After the deploy, we also want to create a zip and upload it to the release on Github. We don't want
      # users to have to go to the repository to find our plugin :).
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        env:
          # Note, this is an exception to action secrets: GH_TOKEN is always available and provides access to
          # the current repository this action runs in.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          # Provide what the file should be named when attached to the release (plugin-name.zip)
          files: ${{ github.workspace }}/${{ github.event.repository.name }}.zip